version: '3'
services:
  postgres:
    container_name: note-postgres
    image: postgres:alpine
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure
  adminer:
    container_name: note-adminer
    image: adminer:standalone
    ports:
      - ${ADMINER_PORT}:8080
    restart: on-failure